CI: Add test reporting.

diff --git a/.github/workflows/test_avian.yml b/.github/workflows/test_avian.yml
--- a/.github/workflows/test_avian.yml
+++ b/.github/workflows/test_avian.yml
@@ -17,18 +17,14 @@ jobs:
     - uses: Swatinem/rust-cache@v2
     - name: Install alsalib headers
       run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
-    - name: Run tests for repository.
-      run: cargo test --no-default-features --features "avian" -- -Z unstable-options --format json --report-time | tee results.json
-    - name: Prepare junit report
-      id: cargo_reporter
-      uses: innoq/action-cargo-test-report@v1
+    - uses: taiki-e/install-action@nextest
+    - name: Test with nextest
+      uses: actions-rs/cargo@v1
       with:
-        cargo-test-report-json: 'results.json'
+        command: nextest
+        args: run --test avian --features "avian" --profile ci
     - name: Publish Test Report
-      uses: mikepenz/action-junit-report@main
-      if: always()
+      uses: mikepenz/action-junit-report@v5
+      if: success() || failure() # always run even if the previous step fails
       with:
-        check_name: Test Report
-        fail_on_failure: true
-        require_tests: true
-        summary: ${{ steps.cargo_reporter.outputs.summary }}
+        report_paths: 'target/nextest/ci/junit.xml'
