CI: Move tests to nextest.

diff --git a/.github/workflows/test_parry.yml b/.github/workflows/test_parry.yml
--- a/.github/workflows/test_parry.yml
+++ b/.github/workflows/test_parry.yml
@@ -1,4 +1,4 @@
-name: Test Parry3d
+name: Test Parry
 
 on:
   workflow_dispatch:
@@ -12,10 +12,23 @@ jobs:
   check:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout repository code.
-      uses: actions/checkout@v4
-    - uses: Swatinem/rust-cache@v2
-    - name: Install alsalib headers
-      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
-    - name: Run tests for repository.
-      run: cargo test --features "parry3d"
+      - name: Checkout repository code.
+        uses: actions/checkout@v4
+      - uses: Swatinem/rust-cache@v2
+      - name: Install alsalib headers
+        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
+      - uses: taiki-e/install-action@nextest
+      - name: Test with nextest
+        uses: actions-rs/cargo@v1
+        with:
+          command: nextest
+          args: run --test parry3d --no-default-features --features "parry3d" --profile ci
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'target/nextest/ci/junit.xml'
+          check_name: Parry3d Test Report
+          include_passed: true
+          detailed_summary: true
+          comment: true
